'use client'
import type { Metadata } from 'next'
import { cookies } from 'next/headers'
import { QueryClientProvider, QueryClient } from 'react-query'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode,
  login: React.ReactNode
}) {
  const queryClient = new QueryClient()

  return (
    <QueryClientProvider client={queryClient}>
        {children}
    </QueryClientProvider>
  )
}
